# Generated by Django 5.2.8 on 2025-11-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.FloatField(blank=True, null=True)),
                ('importance', models.IntegerField(default=5)),
                ('dependencies', models.JSONField(default=list)),
            ],
        ),
    ]
